[tool.poetry]
name = "prueva-despliegue"
version = "0.1.0"
description = ""
authors = ["Brandon <bg4710699@gmail.com>"]
readme = "README.md"
packages = [{include = "prueva_despliegue"}]

[tool.poetry.dependencies]
python = "^3.8"
django = "^4.2.1"
gunicorn = "^21.2.0"
